-- Startbias
insert or replace into StartBiasTerrains
	(CivilizationType,				TerrainType,		Tier)
values
	('CIVILIZATION_CSD_HONOLULU',	'TERRAIN_COAST',	1),
	('CIVILIZATION_CSD_RIGA',		'TERRAIN_COAST',	1),
	('CIVILIZATION_CSD_GENOVA',		'TERRAIN_COAST',	1),
	('CIVILIZATION_CSD_SEVASTOPOL',	'TERRAIN_COAST',	1),
	('CIVILIZATION_CSD_ALGIERS',	'TERRAIN_COAST',	1),
	('CIVILIZATION_CSD_ACAPULCO',	'TERRAIN_COAST',	1);

-- Modifiers in this table are attached to suzerain
create temporary table if not exists TraitAttachedModifiers (
	TraitType text not null,
	ModifierId text not null,
	primary key (TraitType, ModifierId)
);

-- Suzerain Modifiers
-- Kiev
insert or replace into TraitAttachedModifiers
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSD_KIEV_TRAIT',		'MINOR_CIV_CSD_KIEV_GROWTH_RATE_AT_PEACE'),
	('MINOR_CIV_CSD_KIEV_TRAIT',		'MINOR_CIV_CSD_KIEV_PRODUCTION_AT_WAR');
insert or replace into Modifiers
	(ModifierId,									ModifierType,										SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_KIEV_GROWTH_RATE_AT_PEACE',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_GROWTH',			'PLAYER_IS_AT_PEACE_WITH_ALL_MAJORS'),
	('MINOR_CIV_CSD_KIEV_PRODUCTION_AT_WAR',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'PLAYER_IS_AT_WAR_WITH_ANY_MAJOR');
insert or replace into ModifierArguments
	(ModifierId,									Name,		Value)
values
	('MINOR_CIV_CSD_KIEV_GROWTH_RATE_AT_PEACE',	'Amount',	7),
	('MINOR_CIV_CSD_KIEV_PRODUCTION_AT_WAR',		'YieldType',	'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_KIEV_PRODUCTION_AT_WAR',		'Amount',	7);

-- Fergana
insert or replace into TraitAttachedModifiers
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSD_FERGANA_TRAIT',	'MINOR_CIV_CSD_FERGANA_HILL_FOOD');
insert or replace into Modifiers
	(ModifierId,									ModifierType,									SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_FERGANA_HILL_FOOD',				'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',		'PLOT_IS_HILLS_OR_ADJACENT_TO_MOUNTAIN'),
	('MINOR_CIV_CSD_FERGANA_HILL_FOOD_MODIFIER',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',  'PLOT_IS_HILLS');
insert or replace into ModifierArguments
	(ModifierId,									Name,		Value)
values
	('MINOR_CIV_CSD_FERGANA_HILL_FOOD',			'ModifierId',   'MINOR_CIV_CSD_FERGANA_HILL_FOOD_MODIFIER'),
	('MINOR_CIV_CSD_FERGANA_HILL_FOOD_MODIFIER',	'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSD_FERGANA_HILL_FOOD_MODIFIER',	'Amount',	1);

-- Honolulu
insert or replace into TraitAttachedModifiers 
	(TraitType,					ModifierId)
values
	('MINOR_CIV_CSD_HONOLULU_TRAIT',   'MINOR_CIV_CSD_HONOLULU_FISHERY_FOOD'),
	('MINOR_CIV_CSD_HONOLULU_TRAIT',   'MINOR_CIV_CSD_HONOLULU_CITY_FOOD');
insert or replace into Modifiers
	(ModifierId,							ModifierType,									SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_HONOLULU_FISHERY_FOOD',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',				'PLOT_HAS_FISHERY_REQUIREMENTS'),
	('MINOR_CIV_CSD_HONOLULU_CITY_FOOD',	'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',  'PLOT_IS_ADJACENT_TO_COAST');
insert or replace into ModifierArguments
	(ModifierId,							Name,		Value)
values
	('MINOR_CIV_CSD_HONOLULU_FISHERY_FOOD',	'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSD_HONOLULU_FISHERY_FOOD',	'Amount',	1),
	('MINOR_CIV_CSD_HONOLULU_CITY_FOOD',	'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSD_HONOLULU_CITY_FOOD',	'Amount',	2);

--Yangon
insert or replace into TraitAttachedModifiers
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSD_YANGON_TRAIT',	'MINOR_CIV_CSD_YANGON_FARM_FOOD'),
	('MINOR_CIV_CSD_YANGON_TRAIT',	'MINOR_CIV_CSD_YANGON_FARM_PRODUCTION');
insert or replace into Modifiers
	(ModifierId,								ModifierType,						OwnerRequirementSetId,						SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_YANGON_FARM_FOOD',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLAYER_HAS_CIVIC_FEUDALISM_REQUIREMENTS',	'PLOT_HAS_FARM_REQUIREMENTS'),
	('MINOR_CIV_CSD_YANGON_FARM_PRODUCTION',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	null,										'HD_PLOT_HAS_RESOURCE_FARM_REQUIREMENTS');
insert or replace into ModifierArguments
	(ModifierId,								Name,		Value)
values
	('MINOR_CIV_CSD_YANGON_FARM_FOOD',		'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSD_YANGON_FARM_FOOD',		'Amount',	1),
	('MINOR_CIV_CSD_YANGON_FARM_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_YANGON_FARM_PRODUCTION',	'Amount',	1);

--Aswan
insert or replace into TraitAttachedModifiers
	(TraitType,					ModifierId)
values
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_AQUEDUCT_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_DAM_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_CANAL_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_AQUEDUCT_BUILDING_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_DAM_BUILDING_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_TRAIT',   'MINOR_CIV_CSD_ASWAN_CANAL_BUILDING_PRODUCTION');
insert or replace into Modifiers
	(ModifierId,															ModifierType)
values
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_PRODUCTION',							'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_DAM_PRODUCTION',								'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_CANAL_PRODUCTION',								'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_BUILDING_PRODUCTION',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_DAM_BUILDING_PRODUCTION',						'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION'),
	('MINOR_CIV_CSD_ASWAN_CANAL_BUILDING_PRODUCTION',					'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION');

insert or replace into ModifierArguments
	(ModifierId,											Name,			Value)
values
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_PRODUCTION',			'DistrictType',	'DISTRICT_AQUEDUCT'),
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_PRODUCTION',			'Amount',		50),
	('MINOR_CIV_CSD_ASWAN_DAM_PRODUCTION',				'DistrictType',	'DISTRICT_DAM'),
	('MINOR_CIV_CSD_ASWAN_DAM_PRODUCTION',				'Amount',		50),
	('MINOR_CIV_CSD_ASWAN_CANAL_PRODUCTION',				'DistrictType',	'DISTRICT_CANAL'),
	('MINOR_CIV_CSD_ASWAN_CANAL_PRODUCTION',				'Amount',		50),
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_BUILDING_PRODUCTION',	'DistrictType',	'DISTRICT_AQUEDUCT'),
	('MINOR_CIV_CSD_ASWAN_AQUEDUCT_BUILDING_PRODUCTION',	'Amount',		50),
	('MINOR_CIV_CSD_ASWAN_DAM_BUILDING_PRODUCTION',		'DistrictType',	'DISTRICT_DAM'),
	('MINOR_CIV_CSD_ASWAN_DAM_BUILDING_PRODUCTION',		'Amount',		50),
	('MINOR_CIV_CSD_ASWAN_CANAL_BUILDING_PRODUCTION',	'DistrictType',	'DISTRICT_CANAL'),
	('MINOR_CIV_CSD_ASWAN_CANAL_BUILDING_PRODUCTION',	'Amount',		50);

-- Catalhoyuk
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_CATALHOYUK_TRAIT';
create temporary table CatalhoyukResources (ResourceType text not null primary key);
insert or replace into CatalhoyukResources (ResourceType) select ResourceType from Improvement_ValidResources where ImprovementType = 'IMPROVEMENT_PASTURE' or ImprovementType = 'IMPROVEMENT_CAMP';
insert or replace into TraitAttachedModifiers
	(TraitType,						ModifierId)
select
	'MINOR_CIV_CSE_CATALHOYUK_TRAIT',   'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType
from CatalhoyukResources;
insert or replace into Modifiers
	(ModifierId,									ModifierType,							SubjectRequirementSetId)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType,	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',   'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIREMENTS'
from CatalhoyukResources;
insert or replace into Modifiers
	(ModifierId,													ModifierType)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType || '_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS'
from CatalhoyukResources;
insert or replace into ModifierArguments
	(ModifierId,									Name,			Value)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType,	'ModifierId',   'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType || '_MODIFIER'
from CatalhoyukResources;
insert or replace into ModifierArguments
	(ModifierId,													Name,		Value)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType || '_MODIFIER',		'Domestic',	1
from CatalhoyukResources;
insert or replace into ModifierArguments
	(ModifierId,													Name,		Value)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType || '_MODIFIER',		'Amount',	1
from CatalhoyukResources;
insert or replace into ModifierArguments
	(ModifierId,													Name,			Value)
select
	'MINOR_CIV_CSE_CATALHOYUK_' || ResourceType || '_MODIFIER',		'YieldType',	'YIELD_FOOD'
from CatalhoyukResources;

-- Mombasa
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_MOMBASA_TRAIT';
insert or replace into TraitAttachedModifiers
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSE_MOMBASA_TRAIT',	'MINOR_CIV_CSE_MOMBASA_PLANTATION_PRODUCTION'),
	('MINOR_CIV_CSE_MOMBASA_TRAIT',	'MINOR_CIV_CSE_MOMBASA_PLANTATION_GOLD'),
	('MINOR_CIV_CSE_MOMBASA_TRAIT',	'MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_PRODUCTION'),
	('MINOR_CIV_CSE_MOMBASA_TRAIT',	'MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_GOLD');
insert or replace into Modifiers
	(ModifierId,										ModifierType,							SubjectRequirementSetId)
values
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_PRODUCTION',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLOT_HAS_PLANTATION_AND_PLAYER_HAS_EXPLORATION'),
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_GOLD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLOT_HAS_PLANTATION'),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_PRODUCTION',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLOT_HAS_RESOURCE_LUMBER_MILL_AND_PLAYER_HAS_EXPLORATION'),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_GOLD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLOT_HAS_RESOURCE_LUMBER_MILL');
insert or replace into ModifierArguments
	(ModifierId,										Name,		Value)
values
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_PRODUCTION',		'YieldType',	'YIELD_PRODUCTION'),
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_PRODUCTION',		'Amount',		1),
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_GOLD',			'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSE_MOMBASA_PLANTATION_GOLD',			'Amount',		2),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_PRODUCTION',	'Amount',		1),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_GOLD',			'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSE_MOMBASA_LUMBER_MILL_GOLD',			'Amount',		2);

-- Manila
insert or replace into TraitAttachedModifiers 
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSD_MANILA_TRAIT',	'MINOR_CIV_CSD_MANILA_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL_BONUS');
insert or replace into Modifiers
	(ModifierId,																ModifierType)
values
	('MINOR_CIV_CSD_MANILA_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL_BONUS',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL');
insert or replace into ModifierArguments
	(ModifierId,														Name,		Value)
values
	('MINOR_CIV_CSD_MANILA_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL_BONUS',  'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSD_MANILA_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL_BONUS',  'Amount',	2);

-- Riga
insert or replace into TraitAttachedModifiers 
	(TraitType,					ModifierId)
values
	('MINOR_CIV_CSD_RIGA_TRAIT',	'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1'),
	('MINOR_CIV_CSD_RIGA_TRAIT',	'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2'),
	('MINOR_CIV_CSD_RIGA_TRAIT',	'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3');
insert or replace into Modifiers
	(ModifierId,											ModifierType,														SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						'CITY_HAS_DISTRICT_HARBOR_TIER_1_BUILDING_REQUIREMENTS'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1_MODIFIER',   'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',  null),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						'CITY_HAS_DISTRICT_HARBOR_TIER_2_BUILDING_REQUIREMENTS'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2_MODIFIER',   'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',  null),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',						'CITY_HAS_DISTRICT_HARBOR_TIER_3_BUILDING_REQUIREMENTS'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3_MODIFIER',   'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',  null);
insert or replace into ModifierArguments
	(ModifierId,											Name,			Value)
values
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1',			'ModifierId',   'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1_MODIFIER'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1_MODIFIER',   'YieldType',	'YIELD_SCIENCE'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_1_MODIFIER',	'Amount',	1),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2',			'ModifierId',   'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2_MODIFIER'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2_MODIFIER',	'YieldType',	'YIELD_SCIENCE'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_2_MODIFIER',	'Amount',	1),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3',			'ModifierId',   'MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3_MODIFIER'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3_MODIFIER',	'YieldType',	'YIELD_SCIENCE'),
	('MINOR_CIV_CSD_RIGA_SCIENCE_BOUNUS_TIER_3_MODIFIER',	'Amount',	1);

-- Genova
insert or replace into TraitAttachedModifiers 
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSD_GENOVA_TRAIT',  'MINOR_CIV_CSD_GENOVA_HAS_HARBOR_PRODUCTION');
insert or replace into Modifiers
	(ModifierId,									ModifierType,												SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_GENOVA_HAS_HARBOR_PRODUCTION',  'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION',   'CITY_HAS_DISTRICT_HARBOR_REQUIREMENTS');
insert or replace into ModifierArguments
	(ModifierId,									Name,	Value)
values
	('MINOR_CIV_CSD_GENOVA_HAS_HARBOR_PRODUCTION',  'Amount',   50);

-- Sevastopol
insert or replace into TraitAttachedModifiers 
	(TraitType,							ModifierId)
values
	('MINOR_CIV_CSD_SEVASTOPOL_TRAIT',  'MINOR_CIV_CSD_SEVASTOPOL_NAVAL_COMBAT_CAROLEAN');
insert or replace into Modifiers
	(ModifierId,										ModifierType)
values
	('MINOR_CIV_CSD_SEVASTOPOL_NAVAL_COMBAT_CAROLEAN',  'MODIFIER_PLAYER_UNITS_GRANT_ABILITY'),
	('NAVAL_UNUSED_MOVEMENT_COMBAT',					'MODIFIER_SINGLE_UNIT_ADJUST_COMBAT_FOR_UNUSED_MOVEMENT');
insert or replace into ModifierArguments
	(ModifierId,										Name,		Value)
values
	('MINOR_CIV_CSD_SEVASTOPOL_NAVAL_COMBAT_CAROLEAN',  'AbilityType',  'ABILITY_SEVASTOPOL_CAROLEAN'),
	('NAVAL_UNUSED_MOVEMENT_COMBAT',					'Amount',	1);
insert or replace into Types
	(Type,								Kind)
values
	('ABILITY_SEVASTOPOL_CAROLEAN',	'KIND_ABILITY');
insert or replace into TypeTags		
	(Type,								Tag)
values
	('ABILITY_SEVASTOPOL_CAROLEAN',		'CLASS_NAVAL_MELEE'),
	('ABILITY_SEVASTOPOL_CAROLEAN',		'CLASS_NAVAL_RAIDER'),
	('ABILITY_SEVASTOPOL_CAROLEAN',		'CLASS_NAVAL_RANGED');
insert or replace into UnitAbilities 
	(UnitAbilityType,					Inactive) 
values	
	('ABILITY_SEVASTOPOL_CAROLEAN',	1);
insert or replace into UnitAbilityModifiers
	(UnitAbilityType,				ModifierId)
values
	('ABILITY_SEVASTOPOL_CAROLEAN',	'NAVAL_UNUSED_MOVEMENT_COMBAT');

-- Havana
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_HAVANA_TRAIT';
insert or replace into TraitAttachedModifiers 
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSE_HAVANA_TRAIT',  'MINOR_CIV_CSE_HAVANA_BREATHTAKING_CULTURE');
insert or replace into Modifiers
	(ModifierId,									ModifierType,						SubjectRequirementSetId)
values
	('MINOR_CIV_CSE_HAVANA_BREATHTAKING_CULTURE',   'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',	'PLOT_BREATHTAKING_APPEAL');
insert or replace into ModifierArguments
	(ModifierId,									Name,			Value)
values
	('MINOR_CIV_CSE_HAVANA_BREATHTAKING_CULTURE',   'YieldType',	'YIELD_CULTURE'),
	('MINOR_CIV_CSE_HAVANA_BREATHTAKING_CULTURE',	'Amount',	1);

-- Djibouti
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_DJIBOUTI_TRAIT';
insert or replace into TraitAttachedModifiers 
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSE_DJIBOUTI_TRAIT',	'MINOR_CIV_CSE_DJIBOUTI_FOOD'),
	('MINOR_CIV_CSE_DJIBOUTI_TRAIT',	'MINOR_CIV_CSE_DJIBOUTI_PRODUCTION');
insert or replace into Modifiers
	(ModifierId,									ModifierType,								SubjectRequirementSetId)
values
	('MINOR_CIV_CSE_DJIBOUTI_FOOD',				'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',	'DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
	('MINOR_CIV_CSE_DJIBOUTI_FOOD_MODIFIER',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',  'PLOT_HAS_SHALLOW_WATER_AND_ADJACENT_TO_OWNER'),
	('MINOR_CIV_CSE_DJIBOUTI_PRODUCTION',		'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',	'DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'),
	('MINOR_CIV_CSE_DJIBOUTI_PRODUCTION_MODIFIER',  'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',  'PLOT_HAS_SHALLOW_WATER_AND_ADJACENT_TO_OWNER');
insert or replace into ModifierArguments
	(ModifierId,									Name,		Value)
values
	('MINOR_CIV_CSE_DJIBOUTI_FOOD',				'ModifierId',   'MINOR_CIV_CSE_DJIBOUTI_FOOD_MODIFIER'),
	('MINOR_CIV_CSE_DJIBOUTI_FOOD_MODIFIER',		'YieldType',	'YIELD_FOOD'),
	('MINOR_CIV_CSE_DJIBOUTI_FOOD_MODIFIER',		'Amount',	1),
	('MINOR_CIV_CSE_DJIBOUTI_PRODUCTION',		'ModifierId',   'MINOR_CIV_CSE_DJIBOUTI_PRODUCTION_MODIFIER'),
	('MINOR_CIV_CSE_DJIBOUTI_PRODUCTION_MODIFIER',  'YieldType',	'YIELD_PRODUCTION'),
	('MINOR_CIV_CSE_DJIBOUTI_PRODUCTION_MODIFIER',  'Amount',	1);

-- Algiers
insert or replace into TraitAttachedModifiers 
	(TraitType,							ModifierId)
values
	('MINOR_CIV_CSD_ALGIERS_TRAIT',		'MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH'),
	('MINOR_CIV_CSD_ALGIERS_TRAIT',		'MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE');
insert or replace into Modifiers
	(ModifierId,												ModifierType,													SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH',				'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',  						NULL),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH_MODIFIER',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',							NULL),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE',			'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',							NULL),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE_MODIFIER',	'MODIFIER_PLAYER_UNIT_ADJUST_UNIT_EXPERIENCE_MODIFIER',		NULL);
insert or replace into ModifierArguments
	(ModifierId,												Name,			Value)
values
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH',				'AbilityType',	'ABILITY_NAVAL_RAIDER_BONUS_1_HD'),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH_MODIFIER',		'Amount',		3),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE',			'AbilityType',	'ABILITY_NAVAL_RAIDER_BONUS_2_HD'),
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE_MODIFIER',	'Amount',		50);
insert or replace into Types
	(Type,									Kind)
values
	('ABILITY_NAVAL_RAIDER_BONUS_1_HD',		'KIND_ABILITY'),
	('ABILITY_NAVAL_RAIDER_BONUS_2_HD',		'KIND_ABILITY');
insert or replace into TypeTags
	(Type,									Tag)
values
	('ABILITY_NAVAL_RAIDER_BONUS_1_HD',		'CLASS_NAVAL_RAIDER'),
	('ABILITY_NAVAL_RAIDER_BONUS_2_HD',		'CLASS_NAVAL_RAIDER');
insert or replace into UnitAbilities 
	(UnitAbilityType,					Inactive) 
values	
	('ABILITY_NAVAL_RAIDER_BONUS_1_HD',	1),
	('ABILITY_NAVAL_RAIDER_BONUS_2_HD',	1);
insert or replace into UnitAbilityModifiers
	(UnitAbilityType,					ModifierId)
values
	('ABILITY_NAVAL_RAIDER_BONUS_1_HD',	'MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH_MODIFIER'),
	('ABILITY_NAVAL_RAIDER_BONUS_2_HD',	'MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_EXPERIENCE_MODIFIER');
insert or replace into ModifierStrings
	(ModifierId,												Context,				Text)
values
	('MINOR_CIV_CSD_ALGIERS_NAVAL_RAIDE_STRENGTH_MODIFIER',		'Preview',				"+{1_Amount} {LOC_CIVILIZATION_CSD_ALGIERS_NAME}");
-- Acapulco
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSD_ACAPULCO_TRAIT';
insert or replace into TraitAttachedModifiers
    (TraitType,                         ModifierId)
values
    ('MINOR_CIV_CSD_ACAPULCO_TRAIT',    'MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER1'),
    ('MINOR_CIV_CSD_ACAPULCO_TRAIT',    'MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER2'),
	('MINOR_CIV_CSD_ACAPULCO_TRAIT',	'MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3');
insert or replace into Modifiers
    (ModifierId,													ModifierType,									SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER1',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'PLOT_COASTAL_IMPROVEMENTS'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER2',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3',				'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',	'DISTRICT_IS_SPECIALTY_DISTRICT_REQUIREMENTS'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'HD_MAZU_REQUIREMENTS');
insert or replace into ModifierArguments
    (ModifierId,								        Name,			Value)
values
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER1',				'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER1',				'Amount',		3),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER2',				'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER2',				'Amount',		3),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3',				'ModifierId',	'MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3_MODIFIER'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3_MODIFIER',		'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSD_ACAPULCO_IMPROVEMENTS_GOLD_TIER3_MODIFIER',		'Amount',		2);

-- Hormuz
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_HORMUZ_TRAIT';
insert or replace into TraitAttachedModifiers 
	(TraitType,						ModifierId)
values
	('MINOR_CIV_CSE_HORMUZ_TRAIT',	'MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY'),
	('MINOR_CIV_CSE_HORMUZ_TRAIT',	'MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC');
insert or replace into Modifiers
	(ModifierId,												ModifierType,														SubjectRequirementSetId)
values
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY',				'MODIFIER_PLAYER_IMPROVEMENTS_ATTACH_MODIFIER',						'HD_PLOT_HAS_LUXURY_RESOURCE_REQUIREMENTS'),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC',			'MODIFIER_PLAYER_IMPROVEMENTS_ATTACH_MODIFIER',						'HD_PLOT_HAS_STRATEGIC_RESOURCE_REQUIREMENTS'),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY_MODIFIER',	'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC_MODIFIER',	'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',	NULL);
insert or replace into ModifierArguments
	(ModifierId,												Name,			Value)
values
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY',				'ModifierId',	'MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY_MODIFIER'),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC',			'ModifierId',	'MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC_MODIFIER'),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY_MODIFIER',	'Amount',		1),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_LUXURY_MODIFIER',	'YieldType',	'YIELD_GOLD'),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC_MODIFIER',	'Amount',		1),
	('MINOR_CIV_CSE_HORMUZ_TRADEROUTE_GOLD_STRATEGIC_MODIFIER',	'YieldType',	'YIELD_GOLD');

-- Garama
delete from TraitModifiers where TraitType = 'MINOR_CIV_CSE_GARAMA_TRAIT';
insert or replace into TraitAttachedModifiers
    (TraitType,                     ModifierId)
values
    ('MINOR_CIV_CSE_GARAMA_TRAIT',  'MINOR_CIV_CSE_GARAMA_ADJUST_GROWTH_RATE'),
    ('MINOR_CIV_CSE_GARAMA_TRAIT',  'MINOR_CIV_CSE_GARAMA_ADJUST_AMENITY');
insert or replace into Modifiers
    (ModifierId,									    ModifierType,                                           SubjectRequirementSetId)
values
    ('MINOR_CIV_CSE_GARAMA_ADJUST_GROWTH_RATE',         'MODIFIER_PLAYER_CITIES_ADJUST_CITY_GROWTH',            'HD_CITY_HAS_AQUEDUCT_AND_HAS_NO_8_POP'),
    ('MINOR_CIV_CSE_GARAMA_ADJUST_AMENITY',             'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',          'HD_CITY_HAS_AQUEDUCT_AND_HAS_8_POP');
insert or replace into ModifierArguments
	(ModifierId,										Name,		        Value)
values
    ('MINOR_CIV_CSE_GARAMA_ADJUST_GROWTH_RATE',         'Amount',           10),
    ('MINOR_CIV_CSE_GARAMA_ADJUST_AMENITY',             'Amount',           1);

-- Ragusa
insert or replace into TraitAttachedModifiers 
	(TraitType,							ModifierId)
values
	('MINOR_CIV_CSD_RAGUSA_TRAIT',		'MINOR_CIV_CSD_RAGUSA_PLOT_PURCHASE'),
	('MINOR_CIV_CSD_RAGUSA_TRAIT',		'MINOR_CIV_CSD_RAGUSA_OCEAN_PLOT_PURCHASE');
insert or replace into Modifiers
	(ModifierId,									ModifierType)
values
	('MINOR_CIV_CSD_RAGUSA_PLOT_PURCHASE',			'MODIFIER_PLAYER_CITIES_ADJUST_PLOT_PURCHASE_COST'),
	('MINOR_CIV_CSD_RAGUSA_OCEAN_PLOT_PURCHASE',	'MODIFIER_PLAYER_CITIES_ADJUST_PLOT_PURCHASE_COST_TERRAIN');
insert or replace into ModifierArguments
	(ModifierId,										Name,				Value)
values
	('MINOR_CIV_CSD_RAGUSA_PLOT_PURCHASE',				'Amount',			-20),
	('MINOR_CIV_CSD_RAGUSA_OCEAN_PLOT_PURCHASE',		'TerrainType',		'TERRAIN_COAST'),
	('MINOR_CIV_CSD_RAGUSA_OCEAN_PLOT_PURCHASE',		'Amount',			-20);

-- Prague
insert or replace into TraitAttachedModifiers 
	(TraitType,							ModifierId)
values
	('MINOR_CIV_CSD_PRAGUE_TRAIT',		'MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION'),
	('MINOR_CIV_CSD_PRAGUE_TRAIT',		'MINOR_CIV_CSD_PRAGUE_TRADEROUTE_CULTURE'),
--	('MINOR_CIV_CSD_PRAGUE_TRAIT',		'MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATE'),
	('MINOR_CIV_CSD_PRAGUE_TRAIT',		'MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATEST');
insert or replace into Modifiers
	(ModifierId,											ModifierType,													OwnerRequirementSetId)
values
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		null),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_CULTURE',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		'PLAYER_HAS_CIVIC_MEDIEVAL_FAIRES_REQUIREMENTS'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATE',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		'PLAYER_HAS_TECH_APPRENTICESHIP_REQUIREMENTS'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATEST',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',		'PLAYER_HAS_TECH_INDUSTRIALIZATION_REQUIREMENTS');
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
values
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION',			'YieldType',		'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION',			'Amount',			1),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_CULTURE',				'YieldType',		'YIELD_CULTURE'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_CULTURE',				'Amount',			1),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATE',		'YieldType',		'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATE',		'Amount',			1),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATEST',	'YieldType',		'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_PRAGUE_TRADEROUTE_PRODUCTION_LATEST',	'Amount',			1);

-- Florence
insert or replace into TraitAttachedModifiers 
	(TraitType,							ModifierId)
values
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE_LATE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT_LATE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT_LATE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE_LATE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT_LATE'),
	('MINOR_CIV_CSD_FLORENCE_TRAIT',	'MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT_LATE');
insert or replace into Modifiers
	(ModifierId,													ModifierType,											OwnerRequirementSetId,			 SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		null,							'DISTRICT_IS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		null,							'CITY_HAS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		null,							'CITY_HAS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE_LATE',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		'PLAYER_IS_ERA_RENAISSANCE',	'DISTRICT_IS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT_LATE',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'PLAYER_IS_ERA_RENAISSANCE',	'CITY_HAS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT_LATE',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'PLAYER_IS_ERA_RENAISSANCE',	'CITY_HAS_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		null,							'DISTRICT_IS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		null,							'CITY_HAS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		null,							'CITY_HAS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE_LATE',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',		'PLAYER_IS_ERA_RENAISSANCE',	'DISTRICT_IS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT_LATE',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'PLAYER_IS_ERA_RENAISSANCE',	'CITY_HAS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT_LATE',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'PLAYER_IS_ERA_RENAISSANCE',	'CITY_HAS_DISTRICT_INDUSTRIAL_ZONE_REQUIREMENTS');
insert or replace into ModifierArguments
	(ModifierId,													Name,						Value)
values
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE',					'YieldType',				'YIELD_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE',					'Amount',					1),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT',		'GreatPersonClassType',		'GREAT_PERSON_CLASS_WRITER'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT',		'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT',		'GreatPersonClassType',		'GREAT_PERSON_CLASS_ARTIST'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT',		'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE_LATE',				'YieldType',				'YIELD_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_CULTURE_LATE',				'Amount',					1),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT_LATE',	'GreatPersonClassType',		'GREAT_PERSON_CLASS_WRITER'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_WRITER_POINT_LATE',	'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT_LATE',	'GreatPersonClassType',		'GREAT_PERSON_CLASS_ARTIST'),
	('MINOR_CIV_CSD_FLORENCE_COMMERCIAL_GREAT_ARTIST_POINT_LATE',	'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE',					'YieldType',				'YIELD_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE',					'Amount',					1),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT',		'GreatPersonClassType',		'GREAT_PERSON_CLASS_WRITER'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT',		'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT',		'GreatPersonClassType',		'GREAT_PERSON_CLASS_ARTIST'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT',		'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE_LATE',				'YieldType',				'YIELD_CULTURE'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_CULTURE_LATE',				'Amount',					1),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT_LATE',	'GreatPersonClassType',		'GREAT_PERSON_CLASS_WRITER'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_WRITER_POINT_LATE',	'Amount',					2),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT_LATE',	'GreatPersonClassType',		'GREAT_PERSON_CLASS_ARTIST'),
	('MINOR_CIV_CSD_FLORENCE_INDUSTRIAL_GREAT_ARTIST_POINT_LATE',	'Amount',					2);

-- Gundishapur
insert or replace into TraitAttachedModifiers 
	(TraitType,								ModifierId)
values
	('MINOR_CIV_CSD_GUNDISHAPUR_TRAIT',		'MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_GREAT_SCIENTIST_POINT'),
	('MINOR_CIV_CSD_GUNDISHAPUR_TRAIT',		'MINOR_CIV_CSD_GUNDISHAPUR_HOLY_SITE_GREAT_SCIENTIST_POINT'),
	('MINOR_CIV_CSD_GUNDISHAPUR_TRAIT',		'MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_SCIENCE'),
	('MINOR_CIV_CSD_GUNDISHAPUR_TRAIT',		'MINOR_CIV_CSD_GUNDISHAPUR_COMMERCIAL_SCIENCE');
insert or replace into Modifiers
	(ModifierId,													ModifierType,													SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_GREAT_SCIENTIST_POINT',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',				'CITY_HAS_DISTRICT_CAMPUS_REQUIREMENTS'),
	('MINOR_CIV_CSD_GUNDISHAPUR_HOLY_SITE_GREAT_SCIENTIST_POINT',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',				'CITY_HAS_CAMPUS_AND_HOLY_SITE'),
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_SCIENCE',					'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',		'CITY_HAS_DISTRICT_CAMPUS_REQUIREMENTS'),
	('MINOR_CIV_CSD_GUNDISHAPUR_COMMERCIAL_SCIENCE',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',		'CITY_HAS_CAMPUS_AND_COMMERCIAL');
insert or replace into ModifierArguments
	(ModifierId,													Name,						Value)
values
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_GREAT_SCIENTIST_POINT',		'GreatPersonClassType',		'GREAT_PERSON_CLASS_SCIENTIST'),
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_GREAT_SCIENTIST_POINT',		'Amount',					2),
	('MINOR_CIV_CSD_GUNDISHAPUR_HOLY_SITE_GREAT_SCIENTIST_POINT',	'GreatPersonClassType',		'GREAT_PERSON_CLASS_SCIENTIST'),
	('MINOR_CIV_CSD_GUNDISHAPUR_HOLY_SITE_GREAT_SCIENTIST_POINT',	'Amount',					2),
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_SCIENCE',					'YieldType',				'YIELD_SCIENCE'),
	('MINOR_CIV_CSD_GUNDISHAPUR_CAMPUS_SCIENCE',					'Amount',					0.2),
	('MINOR_CIV_CSD_GUNDISHAPUR_COMMERCIAL_SCIENCE',				'YieldType',				'YIELD_SCIENCE'),
	('MINOR_CIV_CSD_GUNDISHAPUR_COMMERCIAL_SCIENCE',				'Amount',					0.2);

-- Vienna
	-- 无外交区
insert or replace into TraitAttachedModifiers 
	(TraitType,								ModifierId)
select
	'MINOR_CIV_CSD_VIENNA_TRAIT',			'MINOR_CIV_CSD_VIENNA_CULTURE'
where not exists (select DistrictType from Districts where DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER');
insert or replace into Modifiers
	(ModifierId,							ModifierType,											SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_VIENNA_CULTURE',		'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',	'CITY_HAS_GOVERNOR');
insert or replace into ModifierArguments
	(ModifierId,							Name,				Value)
values
	('MINOR_CIV_CSD_VIENNA_CULTURE',		'YieldType',		'YIELD_CULTURE'),
	('MINOR_CIV_CSD_VIENNA_CULTURE',		'Amount',			10);

	-- 有外交区
with TraitAttachedModifiers_Pre
	(TraitType,								ModifierId)
as (values
	('MINOR_CIV_CSD_VIENNA_TRAIT',			'MINOR_CIV_CSD_VIENNA_DIPLOMATIC_GREAT_MUSICIAN_POINTS'),
	('MINOR_CIV_CSD_VIENNA_TRAIT',			'MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1'),
	('MINOR_CIV_CSD_VIENNA_TRAIT',			'MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2'))
insert or replace into TraitAttachedModifiers 
	(TraitType,								ModifierId)
select
	TraitType,								ModifierId
from TraitAttachedModifiers_Pre where exists (select DistrictType from Districts where DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER');
with Modifiers_Pre
	(ModifierId,																												ModifierType,																		OwnerRequirementSetId,			SubjectRequirementSetId)
as (values
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_GREAT_MUSICIAN_POINTS',						'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',		null,			'REQUIRES_DISTRICT_IS_DISTRICT_DIPLOMATIC_QUARTER_UDMET'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1',									'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',		null,			null),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2',									'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',		'PLAYER_HAS_CIVIC_DIPLOMATIC_SERVICE_REQUIREMENTS',			null))
insert or replace into Modifiers
	(ModifierId,							ModifierType,											OwnerRequirementSetId,	SubjectRequirementSetId)
select
	ModifierId,								ModifierType,											OwnerRequirementSetId,	SubjectRequirementSetId
from Modifiers_Pre where exists (select DistrictType from Districts where DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER');
with ModifierArguments_Pre
	(ModifierId,											Name,				Value)
as (values
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_GREAT_MUSICIAN_POINTS',				'GreatPersonClassType',			'GREAT_PERSON_CLASS_MUSICIAN'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_GREAT_MUSICIAN_POINTS',				'Amount',			4),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1',		'DistrictType',		'DISTRICT_DIPLOMATIC_QUARTER'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1',		'YieldType',			'YIELD_CULTURE'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1',		'Amount',					1),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_1',		'Description',		'LOC_VIENNA_DIPLOMATIC_CULTURE_TEXT'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2',		'DistrictType',		'DISTRICT_DIPLOMATIC_QUARTER'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2',		'YieldType',			'YIELD_CULTURE'),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2',		'Amount',					1),
	('MINOR_CIV_CSD_VIENNA_DIPLOMATIC_CULTURE_BONUS_2',		'Description',		'LOC_VIENNA_DIPLOMATIC_CULTURE_TEXT'))
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
select
	ModifierId,												Name,				Value
from ModifierArguments_Pre where exists (select DistrictType from Districts where DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER');

-- Volsinii
insert or replace into TraitAttachedModifiers 
	(TraitType,								ModifierId)
values
	('MINOR_CIV_CSD_VOLSINII_TRAIT',		'MINOR_CIV_CSD_VOLSINII_FOOD'),
	('MINOR_CIV_CSD_VOLSINII_TRAIT',		'MINOR_CIV_CSD_VOLSINII_FAITH');
insert or replace into Modifiers
	(ModifierId,							ModifierType,								SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_VOLSINII_FOOD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'PLOT_HAS_BONUS_AND_CITY_HAS_HOLY_SITE'),
	('MINOR_CIV_CSD_VOLSINII_FAITH',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',		'PLOT_HAS_BONUS_AND_CITY_HAS_AQUEDUCT');
insert or replace into ModifierArguments
	(ModifierId,							Name,				Value)
values
	('MINOR_CIV_CSD_VOLSINII_FOOD',			'YieldType',		'YIELD_FOOD'),
	('MINOR_CIV_CSD_VOLSINII_FOOD',			'Amount',			1),
	('MINOR_CIV_CSD_VOLSINII_FAITH',		'YieldType',		'YIELD_FAITH'),
	('MINOR_CIV_CSD_VOLSINII_FAITH',		'Amount',			1);

-- Tirana
insert or replace into TraitAttachedModifiers 
	(TraitType,								ModifierId)
values
	('MINOR_CIV_CSD_TIRANA_TRAIT',			'MINOR_CIV_CSD_TIRANA_MILITARY_ENGINEER_CHARGE'),
	('MINOR_CIV_CSD_TIRANA_TRAIT',			'MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION_ATTACH'),
	('MINOR_CIV_CSD_TIRANA_TRAIT',			'MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY');
insert or replace into Modifiers
	(ModifierId,											ModifierType,												SubjectRequirementSetId)
values
	('MINOR_CIV_CSD_TIRANA_MILITARY_ENGINEER_CHARGE',		'MODIFIER_PLAYER_TRAINED_UNITS_ADJUST_BUILDER_CHARGES',		'UNIT_IS_MILITARY_ENGINEERING_UNITS_REQUIREMENTS'),
	('MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION_ATTACH',			'MODIFIER_PLAYER_IMPROVEMENTS_ATTACH_MODIFIER',				'PLOT_HAS_IMPROVEMENT_FORT_REQUIREMENTS'),
	('MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION',				'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',						'PLOT_HAS_STRATEGIC_ADJACENT_TO_OWNER'),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'MODIFIER_PLAYER_CITIES_IMPROVEMENT_ADJACENCY',					null);
update Modifiers set Permanent = 1 where ModifierId = 'MINOR_CIV_CSD_TIRANA_MILITARY_ENGINEER_CHARGE';

insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
values
	('MINOR_CIV_CSD_TIRANA_MILITARY_ENGINEER_CHARGE',		'Amount',			2),
	('MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION_ATTACH',			'ModifierId',		'MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION'),
	('MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION',				'YieldType',		'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_TIRANA_FORT_PRODUCTION',				'Amount',			1),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'DistrictType',		'DISTRICT_ENCAMPMENT'),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'ImprovementType',	'IMPROVEMENT_FORT'),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'YieldType',		'YIELD_PRODUCTION'),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'Amount',			1),
	('MINOR_CIV_CSD_TIRANA_ENCAMPMENT_FORT_ADJACENCY',		'Description',		'LOC_DISTRICT_FORT_PRODUCTION');

-- Attach modifiers in TraitAttachedModifiers to suzerain
insert or ignore into TraitModifiers
	(TraitType, ModifierId)
select
	TraitType,  ModifierId || '_ATTACH'
from TraitAttachedModifiers;
insert or ignore into Modifiers
	(ModifierId,				ModifierType,							SubjectRequirementSetId)
select
	ModifierId || '_ATTACH',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',	'PLAYER_IS_SUZERAIN'
from TraitAttachedModifiers;
insert or ignore into ModifierArguments
	(ModifierId,				Name,			Value)
select
	ModifierId || '_ATTACH',	'ModifierId',	ModifierId
from TraitAttachedModifiers;
drop table TraitAttachedModifiers;

-- RequirementSets
insert or ignore into RequirementSets
	(RequirementSetId,												RequirementSetType)
values 
	('PLOT_IS_ADJACENT_TO_VOLCANO_OR_FISSURE',						'REQUIREMENTSET_TEST_ANY'),
	('PLOT_IS_IMPROVED_AND_ADJACENT_TO_VOLCANO_OR_FISSURE',			'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_SHALLOW_WATER_AND_ADJACENT_TO_OWNER',				'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_PLANTATION',											'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_PLANTATION_AND_PLAYER_HAS_EXPLORATION',				'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL',								'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL_AND_PLAYER_HAS_EXPLORATION',	'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_FISHERY_REQUIREMENTS',								'REQUIREMENTSET_TEST_ALL'),
	('UNIT_HAS_ABILITY_COASTAL_RAID_REQUIREMENTS',					'REQUIREMENTSET_TEST_ANY'),
	('PLOT_BREATHTAKING_APPEAL',            						'REQUIREMENTSET_TEST_ALL'),
	('PLOT_COASTAL_IMPROVEMENTS',                               	'REQUIREMENTSET_TEST_ALL'),
	('PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY',    	'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_AQUEDUCT_AND_HAS_NO_8_POP',                   	'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_AQUEDUCT_AND_HAS_8_POP',                      	'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_IS_ERA_RENAISSANCE',          			            	'REQUIREMENTSET_TEST_ALL'),
	('CITY_HAS_CAMPUS_AND_HOLY_SITE',          			           	'REQUIREMENTSET_TEST_ALL'),
	('CITY_HAS_CAMPUS_AND_COMMERCIAL',          			        'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_HOLY_SITE',          			    'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_AQUEDUCT',          			    'REQUIREMENTSET_TEST_ALL'),
	('PLOT_HAS_STRATEGIC_ADJACENT_TO_OWNER',          			    'REQUIREMENTSET_TEST_ALL');
insert or ignore into RequirementSetRequirements
	(RequirementSetId,										    	RequirementId)
values
	('PLOT_IS_ADJACENT_TO_VOLCANO_OR_FISSURE',						'REQUIRES_PLOT_ADJACENT_VOLCANO'),
	('PLOT_IS_ADJACENT_TO_VOLCANO_OR_FISSURE',						'PLOT_ADJACENT_TO_GEOTHERMAL_FISSURE_REQUIREMENT'),
	('PLOT_IS_IMPROVED_AND_ADJACENT_TO_VOLCANO_OR_FISSURE',			'REQUIRES_PLOT_IS_IMPROVED'),
	('PLOT_IS_IMPROVED_AND_ADJACENT_TO_VOLCANO_OR_FISSURE',			'REQUIRES_PLOT_ADJACENT_TO_GEOTHERMAL_FISSURE'),
	('PLOT_HAS_SHALLOW_WATER_AND_ADJACENT_TO_OWNER',				'REQUIRES_PLOT_HAS_SHALLOW_WATER'),
	('PLOT_HAS_SHALLOW_WATER_AND_ADJACENT_TO_OWNER',				'ADJACENT_TO_OWNER'),
	('PLOT_HAS_PLANTATION',											'REQUIRES_PLOT_HAS_PLANTATION'),
	('PLOT_HAS_PLANTATION_AND_PLAYER_HAS_EXPLORATION',				'REQUIRES_PLOT_HAS_PLANTATION'),
	('PLOT_HAS_PLANTATION_AND_PLAYER_HAS_EXPLORATION',				'REQUIRES_PLAYER_HAS_CIVIC_EXPLORATION'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL',								'REQUIRES_PLOT_HAS_LUMBER_MILL'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL',								'PLOT_HAS_RESOURCE_REQUIREMENTS'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL_AND_PLAYER_HAS_EXPLORATION',	'REQUIRES_PLOT_HAS_LUMBER_MILL'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL_AND_PLAYER_HAS_EXPLORATION',	'PLOT_HAS_RESOURCE_REQUIREMENTS'),
	('PLOT_HAS_RESOURCE_LUMBER_MILL_AND_PLAYER_HAS_EXPLORATION',	'REQUIRES_PLAYER_HAS_CIVIC_EXPLORATION'),
	('PLOT_HAS_FISHERY_REQUIREMENTS',								'REQUIRES_PLOT_HAS_IMPROVEMENT_FISHERY'),
	('UNIT_HAS_ABILITY_COASTAL_RAID_REQUIREMENTS',					'REQUIRES_UNIT_HAS_ABILITY_COASTAL_RAID'),
	('UNIT_HAS_ABILITY_COASTAL_RAID_REQUIREMENTS',					'REQUIRES_UNIT_HAS_ABILITY_MELEE_COASTAL_RAID'),
	('PLOT_BREATHTAKING_APPEAL',					            	'REQUIRES_PLOT_BREATHTAKING_APPEAL'),
    ('PLOT_COASTAL_IMPROVEMENTS',                               	'REQUIRES_PLOT_IS_IMPROVED'),
    ('PLOT_COASTAL_IMPROVEMENTS',                               	'HD_REQUIRES_PLOT_ADJACENT_TO_COAST'),
    ('PLOT_COASTAL_IMPROVEMENTS',                               	'REQUIRES_PLOT_HAS_NOT_COAST'),
    ('PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY',    	'REQUIRES_PLOT_IS_IMPROVED'),
    ('PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY',    	'HD_REQUIRES_PLOT_ADJACENT_TO_COAST'),
    ('PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY',    	'REQUIRES_PLOT_HAS_NOT_COAST'),
    ('PLOT_COASTAL_IMPROVEMENTS_AND_PLAYER_HAS_CARTOGRAPHY',    	'HD_REQUIRES_PLAYER_HAS_TECH_CARTOGRAPHY'),
    ('HD_CITY_HAS_AQUEDUCT_AND_HAS_NO_8_POP',                   	'REQUIRES_CITY_HAS_NO_8_POPULATION'),
    ('HD_CITY_HAS_AQUEDUCT_AND_HAS_NO_8_POP',                   	'REQUIRES_CITY_HAS_DISTRICT_AQUEDUCT'),
	('HD_CITY_HAS_AQUEDUCT_AND_HAS_8_POP',                      	'REQUIRES_CITY_HAS_8_POPULATION'),
	('HD_CITY_HAS_AQUEDUCT_AND_HAS_8_POP',                      	'REQUIRES_CITY_HAS_DISTRICT_AQUEDUCT'),
	('PLAYER_IS_ERA_RENAISSANCE',                    			  	'REQUIRES_PLAYER_IS_ERA_RENAISSANCE'),
	('CITY_HAS_CAMPUS_AND_HOLY_SITE',                    			'REQUIRES_CITY_HAS_DISTRICT_CAMPUS'),
	('CITY_HAS_CAMPUS_AND_HOLY_SITE',                    			'REQUIRES_CITY_HAS_DISTRICT_HOLY_SITE'),
	('CITY_HAS_CAMPUS_AND_COMMERCIAL',                    			'REQUIRES_CITY_HAS_DISTRICT_CAMPUS'),
	('CITY_HAS_CAMPUS_AND_COMMERCIAL',                    			'REQUIRES_CITY_HAS_DISTRICT_COMMERCIAL_HUB'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_HOLY_SITE',                    	'REQUIRES_PLOT_HAS_BONUS'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_HOLY_SITE',                    	'REQUIRES_CITY_HAS_DISTRICT_HOLY_SITE'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_AQUEDUCT',                    	'REQUIRES_PLOT_HAS_BONUS'),
	('PLOT_HAS_BONUS_AND_CITY_HAS_AQUEDUCT',                    	'REQUIRES_CITY_HAS_DISTRICT_AQUEDUCT'),
	('PLOT_HAS_STRATEGIC_ADJACENT_TO_OWNER',                    	'REQUIRES_PLOT_HAS_STRATEGIC'),
	('PLOT_HAS_STRATEGIC_ADJACENT_TO_OWNER',                    	'ADJACENT_TO_OWNER');
-- Requirements
insert or ignore into Requirements
	(RequirementId,										    RequirementType)
values
	('REQUIRES_PLOT_ADJACENT_TO_GEOTHERMAL_FISSURE',		'REQUIREMENT_REQUIREMENTSET_IS_MET'),
	('REQUIRES_UNIT_HAS_ABILITY_COASTAL_RAID',				'REQUIREMENT_UNIT_HAS_ABILITY'),
	('REQUIRES_UNIT_HAS_ABILITY_MELEE_COASTAL_RAID',		'REQUIREMENT_UNIT_HAS_ABILITY'),
	('REQUIRES_CITY_HAS_NO_8_POPULATION',                   'REQUIREMENT_CITY_HAS_X_POPULATION');
update Requirements set Inverse = 1 where RequirementId = 'REQUIRES_CITY_HAS_NO_8_POPULATION';
insert or ignore into RequirementArguments
	(RequirementId,										Name,				        Value)
values 
	('REQUIRES_PLOT_ADJACENT_TO_GEOTHERMAL_FISSURE',	'RequirementSetId',	        'PLOT_IS_ADJACENT_TO_VOLCANO_OR_FISSURE'),
	('REQUIRES_UNIT_HAS_ABILITY_COASTAL_RAID',			'UnitAbilityType',		    'ABILITY_COASTAL_RAID'),
	('REQUIRES_UNIT_HAS_ABILITY_MELEE_COASTAL_RAID',	'UnitAbilityType',		    'ABILITY_MELEE_COASTAL_RAID'),
	('REQUIRES_CITY_HAS_NO_8_POPULATION',               'Amount',                   8);

insert or ignore into RequirementSets
	(RequirementSetId, 							    RequirementSetType)
values
	('HD_CSE_AGRICULTURAL_SUZERAIN_1_REQUIREMENTS',     'REQUIREMENTSET_TEST_ALL'),
	('HD_CSE_MARITIME_SUZERAIN_1_REQUIREMENTS',         'REQUIREMENTSET_TEST_ALL'),
	('HD_CSE_AGRICULTURAL_SUZERAIN_2_REQUIREMENTS',     'REQUIREMENTSET_TEST_ALL'),
	('HD_CSE_MARITIME_SUZERAIN_2_REQUIREMENTS',         'REQUIREMENTSET_TEST_ALL');

insert or ignore into RequirementSetRequirements
	(RequirementSetId, 							    RequirementId)
values
	('HD_CSE_AGRICULTURAL_SUZERAIN_1_REQUIREMENTS',     'HD_CSE_AGRICULTURAL_SUZERAIN_1_LEADER'),
	('HD_CSE_MARITIME_SUZERAIN_1_REQUIREMENTS',         'HD_CSE_MARITIME_SUZERAIN_1_LEADER'),
	('HD_CSE_AGRICULTURAL_SUZERAIN_2_REQUIREMENTS',     'HD_CSE_AGRICULTURAL_SUZERAIN_2_LEADER'),
	('HD_CSE_MARITIME_SUZERAIN_2_REQUIREMENTS',         'HD_CSE_MARITIME_SUZERAIN_2_LEADER');

insert or ignore into Requirements
	(RequirementId,								RequirementType)
values
	('HD_CSE_AGRICULTURAL_SUZERAIN_1_LEADER',       'REQUIREMENT_PLAYER_IS_SUZERAIN_X_TYPE'),
	('HD_CSE_MARITIME_SUZERAIN_1_LEADER',           'REQUIREMENT_PLAYER_IS_SUZERAIN_X_TYPE'),
	('HD_CSE_AGRICULTURAL_SUZERAIN_2_LEADER',       'REQUIREMENT_PLAYER_IS_SUZERAIN_X_TYPE'),
	('HD_CSE_MARITIME_SUZERAIN_2_LEADER',           'REQUIREMENT_PLAYER_IS_SUZERAIN_X_TYPE');

insert or ignore into RequirementArguments
	(RequirementId,								Name,				Value)
values
	('HD_CSE_AGRICULTURAL_SUZERAIN_1_LEADER',       'Amount',           1),
	('HD_CSE_MARITIME_SUZERAIN_1_LEADER',           'Amount',           1),
	('HD_CSE_AGRICULTURAL_SUZERAIN_1_LEADER',       'LeaderType',       'LEADER_MINOR_CIV_CSE_AGRICULTURAL'),
	('HD_CSE_MARITIME_SUZERAIN_1_LEADER',           'LeaderType',       'LEADER_MINOR_CIV_CSE_MARITIME'),
	('HD_CSE_AGRICULTURAL_SUZERAIN_2_LEADER',       'Amount',           2),
	('HD_CSE_MARITIME_SUZERAIN_2_LEADER',           'Amount',           2),
	('HD_CSE_AGRICULTURAL_SUZERAIN_2_LEADER',       'LeaderType',       'LEADER_MINOR_CIV_CSE_AGRICULTURAL'),
	('HD_CSE_MARITIME_SUZERAIN_2_LEADER',           'LeaderType',       'LEADER_MINOR_CIV_CSE_MARITIME');

-- Resume 
UPDATE CityNames
SET CityName = "LOC_CITY_NAME_SAMARKAND"
WHERE CityName = "LOC_CITY_NAME_CSE_BUKHARA"
AND CivilizationType = "CIVILIZATION_SAMARKAND";

UPDATE CivilizationLeaders
SET CapitalName = "LOC_CITY_NAME_SAMARKAND"
WHERE CivilizationType = "CIVILIZATION_SAMARKAND";

UPDATE CityNames
SET CityName = "LOC_CITY_NAME_NALANDA"
WHERE CityName = "LOC_CITY_NAME_CSE_TAXILA"
AND CivilizationType = "CIVILIZATION_CSE_NALANDA";

UPDATE CivilizationLeaders
SET CapitalName = "LOC_CITY_NAME_NALANDA"
WHERE CivilizationType = "CIVILIZATION_CSE_NALANDA";